// @generated by torchgen/gen.py from HostTraceFunctor.cuh
// The functor the CUDA kernel host of ${name} launches, named so the traced
// sibling compiled into the same translation unit (HostTraceSibling_*.cuh)
// instantiates the one kernel with it (DECISIONS E36); its device body is the
// ufunc header's, the only copy. Included by that host's .cu before the launch.
#pragma once
#include <ATen/AccumulateType.h>
#include <ATen/OpMathType.h>
#include <${header}>

namespace at::native {
${functors}
} // namespace at::native
