// @generated by torchgen/gen.py from HostTraceSibling.cuh
// ${name} on the traced sibling iterator (aten/src/ATen/cuda/host_trace/ti):
// the entry, the proxies through which the functor's constant fields (a CPU
// scalar operand, a Scalar argument) reach the kernel as values of the tape,
// and their views inside a strided launch. Included once, at the end of the
// translation unit whose host launches the functor, so both instantiate the
// one kernel (DECISIONS E36).
#include <ATen/cuda/host_trace/ti/GenSupport.h>
#include <ATen/HostTraceSiblingOps.h>
${functor_include}
#include <ATen/AccumulateType.h>
#include <ATen/Dispatch.h>
#include <ATen/OpMathType.h>

#ifndef AT_PER_OPERATOR_HEADERS
#include <ATen/Functions.h>
#else
#include <ATen/ops/empty_like.h>
#endif

#include <cstddef>
#include <string_view>

namespace at::cuda::host_trace {
${proxies}
} // namespace at::cuda::host_trace

namespace at::cuda::host_trace::ti {
${views}
} // namespace at::cuda::host_trace::ti

namespace at::cuda::host_trace::ti::gen {
${entry}
} // namespace at::cuda::host_trace::ti::gen
