// @generated by torchgen/gen.py from HostTraceSiblingOps.h
// The generated traced siblings (HostTraceSibling_*.cu): one entry per op,
// what the op's CUDA kernel host does around gpu_kernel on the sibling
// iterator; `out` is the in-place or out= destination, undefined for the
// allocating form. Called by the trace mode in place of the op through
// HostTraceSiblingBindings.h; outside a trace it runs the same launches in
// ordinary mode.
#pragma once
#include <ATen/core/Tensor.h>
#include <c10/core/Scalar.h>

#include <string_view>

namespace at::cuda::host_trace::ti::gen {

${declarations}

} // namespace at::cuda::host_trace::ti::gen
