// @generated by torchgen/gen.py from HostTraceSiblingBindings.h
// Python bindings of the generated traced siblings, included by
// torch/csrc/cuda/HostTraceTI.cpp after its pybind includes: `operand` wraps a
// Python number as the dispatcher's wrapped scalar tensor, `scalar_arg` reads
// a Scalar argument. `_host_trace_ti_gen_siblings` lists (functional overload,
// binding, the overloads served through the same entry, tensor arity, hand
// entry) for torch/cuda/_host_trace_ti.py's registry.
#pragma once
#include <ATen/HostTraceSiblingOps.h>

#include <optional>
#include <string>
#include <tuple>
#include <vector>

template <class Module, class Operand, class ScalarArg>
void host_trace_sibling_bindings(Module& m, Operand operand, ScalarArg scalar_arg) {
  namespace gen = at::cuda::host_trace::ti::gen;
  (void)operand;
  (void)scalar_arg;
${bindings}
  m.def("_host_trace_ti_gen_siblings", []() {
    return std::vector<std::tuple<std::string, std::string, std::vector<std::string>, int, bool>>{
${table}
    };
  });
}
