#define TORCH_ASSERT_NO_OPERATORS
#include <ATen/Dispatch.h>
#include <ATen/native/DispatchStub.h>
#include <ATen/native/cuda/Loops.cuh>
#include <ATen/native/BinaryOps.h>
#include <ATen/HostTraceFunctor_remainder_Tensor.cuh>
#include <ATen/native/TensorIterator.h>
#include <c10/util/TypeSafeSignMath.h>

#include <limits>
#include <type_traits>

// NOTE: CUDA on Windows requires that the enclosing function
// of a __device__ lambda not have internal linkage.

namespace at::native {

// the device bodies live in ATen/native/ufunc/remainder.h (the uint8
// zero-divisor value of the CUDA path included), launched as the generated
// functor by this host and by the traced sibling at the end of this file
void remainder_kernel_cuda(TensorIteratorBase& iter) {
  if (isIntegralType(iter.common_dtype(), /*includeBool*/ false)) {
    AT_DISPATCH_INTEGRAL_TYPES(iter.common_dtype(), "remainder_cuda", [&]() {
      gpu_kernel_with_scalars(iter, CUDAFunctor_remainder_Tensor<scalar_t>{});
    });
  } else {
    AT_DISPATCH_FLOATING_TYPES_AND2(kHalf, kBFloat16, iter.common_dtype(), "remainder_cuda", [&]() {
      gpu_kernel_with_scalars(iter, CUDAFunctor_remainder_Tensor<scalar_t>{});
    });
  }
}

void fmod_kernel_cuda(TensorIteratorBase& iter) {
  if (isIntegralType(iter.common_dtype(), /*includeBool*/ false)) {
    AT_DISPATCH_INTEGRAL_TYPES(iter.common_dtype(), "fmod_cuda", [&]() {
      gpu_kernel_with_scalars(iter, []GPU_LAMBDA(scalar_t a, scalar_t b) -> scalar_t {
        return a % b;
      });
    });
  } else {
    AT_DISPATCH_FLOATING_TYPES_AND2(kHalf, kBFloat16, iter.common_dtype(), "fmod_cuda", [&]() {
      gpu_kernel_with_scalars(iter,
        []GPU_LAMBDA(scalar_t a, scalar_t b) __ubsan_ignore_float_divide_by_zero__ -> scalar_t {
          return ::fmod(a, b);
        });
    });
  }
}

REGISTER_DISPATCH(remainder_stub, &remainder_kernel_cuda)
REGISTER_DISPATCH(fmod_stub, &fmod_kernel_cuda)

} // namespace at::native

// ---- host tracing (ATen/cuda/host_trace): the traced sibling of remainder_kernel_cuda, compiled here
// so the sibling and the host above instantiate the one kernel (DECISIONS E36): the tape's
// launch is eager's function object, not a twin. Generated by torchgen from
// cuda/host_trace/ti/siblings.yaml or the op's ufunc_inner_loop; the entry, its proxies and
// its strided views. Outside a trace it runs the same launches in ordinary mode.
#undef TORCH_ASSERT_NO_OPERATORS
#define TORCH_ASSERT_ONLY_METHOD_OPERATORS
#include <ATen/HostTraceSibling_remainder_Tensor.cuh>
