"""Generate ht/kernel_params_fields.h: fi_ht::KernelParamsFields, one fi_ht::Field per member of the stock
::KernelParams (include/flashinfer/trtllm/fmha/kernelParams.h), in declaration order, from the compiler's DWARF.
Each member's type and offset come from the compiler itself (decltype / offsetof); DWARF gives only the names.

    python ht/gen_fields.py   (run by build.py when the header is missing or older than kernelParams.h)
"""

import os
import re
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import build_flags  # noqa: E402


def dwarf_members(obj: str, struct: str) -> list[str]:
    text = subprocess.run(["eu-readelf", "--debug-dump=info", obj], capture_output=True, text=True, check=True).stdout
    die_re = re.compile(r"^ \[\s*([0-9a-f]+)\](\s+)(\w+)\s+abbrev")
    attr_re = re.compile(r"^\s+(\w+)\s+\((\w+)\)\s+(.*)$")
    dies, stack, cur = {}, [], None
    for line in text.splitlines():
        m = die_re.match(line)
        if m:
            off, indent, tag = int(m.group(1), 16), len(m.group(2)), m.group(3)
            while stack and stack[-1][0] >= indent:
                stack.pop()
            parent = stack[-1][1] if stack else None
            dies[off] = {"tag": tag, "attrs": {}, "children": []}
            if parent is not None:
                dies[parent]["children"].append(off)
            stack.append((indent, off))
            cur = off
            continue
        m = attr_re.match(line)
        if m and cur is not None:
            dies[cur]["attrs"][m.group(1)] = m.group(3).strip().strip('"')
    for d in dies.values():
        if d["tag"] == "structure_type" and d["attrs"].get("name") == struct and "byte_size" in d["attrs"]:
            return [dies[c]["attrs"]["name"] for c in d["children"]
                    if dies[c]["tag"] == "member" and "data_member_location" in dies[c]["attrs"]]
    raise KeyError(struct)


def main() -> None:
    out = os.path.join(HERE, "kernel_params_fields.h")
    with tempfile.TemporaryDirectory() as tmp:
        src = os.path.join(tmp, "probe.cu")
        with open(src, "w") as f:
            f.write("#include <flashinfer/trtllm/fmha/kernelParams.h>\nKernelParams fi_ht_probe;\n")
        obj = os.path.join(tmp, "probe.o")
        cmd = [build_flags.NVCC, "-g", "-c", src, "-o", obj, *build_flags.stock_cuda_flags()]
        subprocess.run(cmd, check=True)
        names = dwarf_members(obj, "KernelParams")
    lines = [
        "// GENERATED by ht/gen_fields.py from the DWARF of the stock ::KernelParams; do not edit.",
        "#pragma once",
        "",
        "namespace fi_ht {",
        "struct KernelParamsFields : ProxyBase<KernelParamsFields> {",
    ]
    for n in names:
        lines.append(f"  Field<decltype(::KernelParams::{n}), offsetof(::KernelParams, {n})> {n};")
    lines += ["", "  void pack(Packer& p) const {", "    p.image.assign(sizeof(::KernelParams), 0);"]
    lines += [f"    {n}.pack(p);" for n in names]
    lines += ["  }", "};", "}  // namespace fi_ht", ""]
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"KernelParams: {len(names)} members -> {out}")


if __name__ == "__main__":
    main()
